//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swertres.Web.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bet
    {
        public long BetID { get; set; }
        public long DrawID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool IsRumble { get; set; }
        public Nullable<long> RowCreatedUserID { get; set; }
        public Nullable<long> RowModifiedUserID { get; set; }
        public Nullable<System.DateTime> RowCreatedDateTime { get; set; }
        public Nullable<System.DateTime> RowModifiedDateTime { get; set; }
        public bool IsDouble { get; set; }
        public Nullable<long> SourceID { get; set; }
    }
}
