//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swertres.Web.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Draw
    {
        public long DrawID { get; set; }
        public string ControlNumber { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> RowCreatedDateTime { get; set; }
        public Nullable<System.DateTime> RowModifiedDateTime { get; set; }
        public Nullable<long> RowCreatedUserID { get; set; }
        public Nullable<long> RowModifiedUserID { get; set; }
        public bool IsEnded { get; set; }
    }
}
