//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swertres.Web.Models.DB
{
    using System;
    
    public partial class GetTargetBetSummary_Result1
    {
        public Nullable<int> Number { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> TotalExcess { get; set; }
    }
}
