//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swertres.Web.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SwertresEntities : DbContext
    {
        public SwertresEntities()
            : base("name=SwertresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bet> Bets { get; set; }
        public virtual DbSet<BetLimit> BetLimits { get; set; }
        public virtual DbSet<Draw> Draws { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    
        public virtual int GetBetOverAllSummary(Nullable<long> drawID)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetBetOverAllSummary", drawIDParameter);
        }
    
        public virtual ObjectResult<GetDoubleBetSummary_Result> GetDoubleBetSummary(Nullable<long> drawID)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDoubleBetSummary_Result>("GetDoubleBetSummary", drawIDParameter);
        }
    
        public virtual ObjectResult<GetRumbleBetSummary_Result> GetRumbleBetSummary(Nullable<long> drawID)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRumbleBetSummary_Result>("GetRumbleBetSummary", drawIDParameter);
        }
    
        public virtual ObjectResult<GetTargetBetSummary_Result1> GetTargetBetSummary(Nullable<long> drawID)
        {
            var drawIDParameter = drawID.HasValue ?
                new ObjectParameter("DrawID", drawID) :
                new ObjectParameter("DrawID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTargetBetSummary_Result1>("GetTargetBetSummary", drawIDParameter);
        }
    }
}
